[2024-06-24 14:56:56,937] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_taskflow_api_v02.get_name 2024-01-19T00:00:00+00:00 [queued]>
[2024-06-24 14:56:57,371] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_taskflow_api_v02.get_name 2024-01-19T00:00:00+00:00 [queued]>
[2024-06-24 14:56:57,384] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:56:57,399] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-24 14:56:57,412] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:56:57,886] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2024-01-19T00:00:00+00:00
[2024-06-24 14:56:57,910] {standard_task_runner.py:52} INFO - Started process 27858 to run task
[2024-06-24 14:56:57,982] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_taskflow_api_v02', 'get_name', '2024-01-19T00:00:00+00:00', '--job-id', '10002', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmp2fugt1s8', '--error-file', '/tmp/tmpe7o95mlm']
[2024-06-24 14:56:58,063] {standard_task_runner.py:77} INFO - Job 10002: Subtask get_name
[2024-06-24 14:56:58,837] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_taskflow_api_v02.get_name 2024-01-19T00:00:00+00:00 [running]> on host 799b1e36e3f1
[2024-06-24 14:57:00,032] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_with_taskflow_api_v02
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2024-01-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-19T00:00:00+00:00
[2024-06-24 14:57:01,157] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_api_v02, task_id=get_name, execution_date=20240119T000000, start_date=20240624T145656, end_date=20240624T145701
[2024-06-24 14:57:03,547] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-06-24 14:57:03,680] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 27858
[2024-06-24 14:57:04,543] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-24 14:57:04,673] {process_utils.py:66} INFO - Process psutil.Process(pid=27858, status='terminated', exitcode=1, started='14:56:56') (27858) terminated with exit code 1
