[2024-06-24 15:03:52,097] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2024-02-15T00:00:00+00:00 [queued]>
[2024-06-24 15:03:52,166] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2024-02-15T00:00:00+00:00 [queued]>
[2024-06-24 15:03:52,168] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 15:03:52,169] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-24 15:03:52,170] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 15:03:52,259] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2024-02-15T00:00:00+00:00
[2024-06-24 15:03:52,273] {standard_task_runner.py:52} INFO - Started process 31330 to run task
[2024-06-24 15:03:52,288] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'second_task', '2024-02-15T00:00:00+00:00', '--job-id', '10912', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmppzsd01x2', '--error-file', '/tmp/tmp4izi2f5j']
[2024-06-24 15:03:52,297] {standard_task_runner.py:77} INFO - Job 10912: Subtask second_task
[2024-06-24 15:03:52,554] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.second_task 2024-02-15T00:00:00+00:00 [running]> on host 799b1e36e3f1
[2024-06-24 15:03:52,801] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-15T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-15T00:00:00+00:00
[2024-06-24 15:03:52,805] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2024-06-24 15:03:52,812] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2024-06-24 15:03:52,840] {bash.py:169} INFO - Output:
[2024-06-24 15:03:52,847] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2024-06-24 15:03:52,857] {bash.py:177} INFO - Command exited with return code 0
[2024-06-24 15:03:53,122] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20240215T000000, start_date=20240624T150352, end_date=20240624T150353
[2024-06-24 15:03:53,233] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24 15:03:53,282] {local_task_job.py:146} INFO - Task exited with return code 0
