[2024-06-24 12:57:05,021] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2021-11-14T00:00:00+00:00 [queued]>
[2024-06-24 12:57:05,295] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2021-11-14T00:00:00+00:00 [queued]>
[2024-06-24 12:57:05,301] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 12:57:05,306] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-24 12:57:05,311] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 12:57:05,446] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2021-11-14T00:00:00+00:00
[2024-06-24 12:57:05,537] {standard_task_runner.py:52} INFO - Started process 32260 to run task
[2024-06-24 12:57:05,564] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'second_task', '2021-11-14T00:00:00+00:00', '--job-id', '1659', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp93p8f9_0', '--error-file', '/tmp/tmp2plxc6lw']
[2024-06-24 12:57:05,587] {standard_task_runner.py:77} INFO - Job 1659: Subtask second_task
[2024-06-24 12:57:05,944] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.second_task 2021-11-14T00:00:00+00:00 [running]> on host 799b1e36e3f1
[2024-06-24 12:57:06,295] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-14T00:00:00+00:00
[2024-06-24 12:57:06,297] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2024-06-24 12:57:06,300] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2024-06-24 12:57:06,337] {bash.py:169} INFO - Output:
[2024-06-24 12:57:06,343] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2024-06-24 12:57:06,346] {bash.py:177} INFO - Command exited with return code 0
[2024-06-24 12:57:06,509] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20211114T000000, start_date=20240624T125705, end_date=20240624T125706
[2024-06-24 12:57:06,728] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24 12:57:06,899] {local_task_job.py:146} INFO - Task exited with return code 0
