[2024-06-24 14:54:37,988] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2023-11-15T00:00:00+00:00 [queued]>
[2024-06-24 14:54:38,161] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2023-11-15T00:00:00+00:00 [queued]>
[2024-06-24 14:54:38,166] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:54:38,168] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-24 14:54:38,171] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:54:38,400] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2023-11-15T00:00:00+00:00
[2024-06-24 14:54:38,447] {standard_task_runner.py:52} INFO - Started process 26932 to run task
[2024-06-24 14:54:38,505] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'second_task', '2023-11-15T00:00:00+00:00', '--job-id', '9786', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmprjcvhruo', '--error-file', '/tmp/tmp4hhyegyl']
[2024-06-24 14:54:38,586] {standard_task_runner.py:77} INFO - Job 9786: Subtask second_task
[2024-06-24 14:55:00,982] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.second_task 2023-11-15T00:00:00+00:00 [running]> on host 799b1e36e3f1
[2024-06-24 14:55:01,580] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2023-11-15T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-15T00:00:00+00:00
[2024-06-24 14:55:01,668] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2024-06-24 14:55:01,706] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2024-06-24 14:55:01,915] {bash.py:169} INFO - Output:
[2024-06-24 14:55:01,931] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2024-06-24 14:55:01,936] {bash.py:177} INFO - Command exited with return code 0
[2024-06-24 14:55:02,378] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20231115T000000, start_date=20240624T145437, end_date=20240624T145502
[2024-06-24 14:55:03,242] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24 14:55:03,624] {local_task_job.py:146} INFO - Task exited with return code 0
