[2024-07-23 11:11:18,172] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2024-07-16T00:00:00+00:00 [queued]>
[2024-07-23 11:11:18,488] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2024-07-16T00:00:00+00:00 [queued]>
[2024-07-23 11:11:18,517] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-07-23 11:11:18,520] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-07-23 11:11:18,524] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-07-23 11:11:18,662] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2024-07-16T00:00:00+00:00
[2024-07-23 11:11:18,736] {standard_task_runner.py:52} INFO - Started process 265 to run task
[2024-07-23 11:11:18,768] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'second_task', '2024-07-16T00:00:00+00:00', '--job-id', '12468', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpezcl5y4j', '--error-file', '/tmp/tmp160kr_dg']
[2024-07-23 11:11:18,792] {standard_task_runner.py:77} INFO - Job 12468: Subtask second_task
[2024-07-23 11:11:18,938] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.second_task 2024-07-16T00:00:00+00:00 [running]> on host 799b1e36e3f1
[2024-07-23 11:11:19,367] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2024-07-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-16T00:00:00+00:00
[2024-07-23 11:11:19,376] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2024-07-23 11:11:19,398] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2024-07-23 11:11:19,578] {bash.py:169} INFO - Output:
[2024-07-23 11:11:19,671] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2024-07-23 11:11:19,690] {bash.py:177} INFO - Command exited with return code 0
[2024-07-23 11:11:20,361] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20240716T000000, start_date=20240723T111118, end_date=20240723T111120
[2024-07-23 11:11:20,703] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-23 11:11:20,770] {local_task_job.py:146} INFO - Task exited with return code 0
